### ISSUE TITLE
Typescript declarations

### ISSUE THREAD

**Issue by rosskevin** [ctavan/jupp#18]
Hey @ctavan - are you interested in including a typescript `index.d.ts` here for us typescript users?  I can PR it and a test if you are willing to accept.

**Comment by ctavan** [comment]
@rosskevin sure! I'm not using TS currently so I can't guarantee maintenance but I'm happy to accept PRs.

**Comment by rosskevin** [comment]
Great!  I think they are good to go as I have them, but I'll wait for a complete once-through on my app then submit a PR.

**Comment by rosskevin** [comment]
@ctavan I started with the yup definitions and have been fixing from there.  I'm almost through it but I found a few problems with type definitions and the lib:

## default
```js
mixed.default(value: any): Schema // chained schema
mixed.default(): any // obtain a default value generated by the schema
```

These are two entirely different methods with the same name.  I've actually never seen anything like it - especially in a public API.  There is simply no way to type it both ways.

I feel like this is a good place to start with divergence from the original, if nothing else, at least for typescript users.

How about changing or aliasing the one method to `defaultValue(): any` - self describing and differentiated?

## setLocale
`setLocale` is actually not imported/exported by the index.  I can type it as a sub-module but it would be more consistent to export it at the index level.

Thoughts?

**Comment by ctavan** [comment]
@rosskevin I'm fine with both your suggestions: a) rename the method to `defaultValue()` and b) export `setLocale`. Feel free to implement this and I'll be happy to merge it.

**Comment by rosskevin** [comment]
If we can get #29 and #28 merged I'm ready to PR the ts definitions.

**Comment by ctavan** [comment]
Meanwhile, the original project has typescript support: https://github.com/jquense/yup#typescript-support
